#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "Usage: <client-id>" >&2
    exit 1
fi

# repack tar & make executable
tar -xvf labwork.tar.gz >/dev/null

chmod +x labwork/*
chmod +x labwork/rc4-bonus/*

rm labwork/labwork*.json
rm -r labwork/c/.idea
rm -r labwork/c/cmake-*
rm -r labwork/memcmp-sidechannel/.idea
rm -r labwork/memcmp-sidechannel/cmake-*
rm labwork.tar.gz

tar -czvf labwork.tar.gz labwork >/dev/null

rm -r labwork

# test for all labs
labs=("labwork01" "labwork02" "labwork03" "labwork04" "labwork05" "labwork06" "labwork08")
for lab in "${labs[@]}"; do
    ./labwork-execute "https://dhbw.johannes-bauer.com/lwsub" "$1" "$lab"
done

rm -r extracted