#!/bin/bash

if [[ "$#" -ne 1 ]]; then
    echo "Usage: <client-id>" >&2
    exit 1
fi

# repack tar & make executable
tar -xvf labwork.tar.gz >/dev/null
chmod +x labwork/*
chmod +x rc4-bonus/*
rm labwork.tar.gz
tar -czvf labwork.tar.gz labwork rc4-bonus >/dev/null
rm -r labwork

# test for all labs
labs=("labwork01" "labwork02" "labwork03" "labwork04" "labwork05")
for lab in "${labs[@]}"; do
    ./labwork-execute "https://dhbw.johannes-bauer.com/lwsub" "$1" "$lab"
done

rm -r extracted